/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.fcys.programacion2.frames;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import ni.edu.uni.fcys.programacaion2.Panels.Calculator;
import ni.edu.uni.fcys.programacaion2.Panels.Temperatura;
import ni.edu.uni.fcys.programacion2.Controllers.CalculatorController;
import ni.edu.uni.fcys.programacion2.Controllers.TemperaturaController;

/**
 *
 * @author LENOVO 17
 */
public class CoversionApp extends javax.swing.JFrame {

    /**
     * Creates new form CoversionApp
     */
    private Calculator calculator;
    private CalculatorController controller;
    private Temperatura temperatura;
    private TemperaturaController temperaturaController;
    public CoversionApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MniCalc = new javax.swing.JMenuItem();
        MniTemp = new javax.swing.JMenuItem();
        MniMoneda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        MniCalc.setText("Calculadora");
        MniCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniCalcActionPerformed(evt);
            }
        });
        jMenu1.add(MniCalc);

        MniTemp.setText("Conversion Temperatura");
        MniTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniTempActionPerformed(evt);
            }
        });
        jMenu1.add(MniTemp);

        MniMoneda.setText("Moneda");
        jMenu1.add(MniMoneda);
        jMenu1.add(jSeparator1);

        MniSalir.setText("Salir");
        MniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MniSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(583, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniSalirActionPerformed
        // TODO add your handling code here:
        int opcion=JOptionPane.showConfirmDialog(null, "Esta Seguro que quiere cerrar la aplicacion","Confirmacion de cierre",JOptionPane.YES_NO_OPTION
        ,JOptionPane.QUESTION_MESSAGE);
        if(opcion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MniSalirActionPerformed

    private void MniCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniCalcActionPerformed
        // TODO add your handling code here:
        if ( calculator== null) {
            calculator = new Calculator();
            controller = new CalculatorController(calculator);
        }

        addComponent(calculator);
    }//GEN-LAST:event_MniCalcActionPerformed

    private void MniTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniTempActionPerformed
        // TODO add your handling code here:
        if(temperatura==null){
            temperatura=new Temperatura();
            temperaturaController=new TemperaturaController(temperatura);
            
        }
        addComponent(temperatura);
    }//GEN-LAST:event_MniTempActionPerformed

    private void addComponent(JComponent component) {
        pnlContent.removeAll();
        pnlContent.add(component, BorderLayout.CENTER);
        
        validate();
        repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoversionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoversionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoversionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoversionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoversionApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MniCalc;
    private javax.swing.JMenuItem MniMoneda;
    private javax.swing.JMenuItem MniSalir;
    private javax.swing.JMenuItem MniTemp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
